[feat] generate turboOCI index from a gzip stream buffer
containerd/overlaybd pull request #264
Opened 2023-09-11 15:53 UTC by BigVan

**What this PR does / why we need it**:

To make overlaybd can build a TurboOCI index from a stream buffer, 
which can make the building process of turboOCI faster.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Please check the following list**:
- [x]  Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [ ]  Does this change require a documentation update?
- [x]  Does this introduce breaking changes that would require an announcement or bumping the major version?
- [ ]  Do all new files have an appropriate license header?

2023-09-11 16:00 UTC, BigVan commented
It is better to merge this PR after v1.0 has been released

2023-12-08 03:38 UTC, yuchen0cc requested changes

2023-12-08 03:38 UTC, yuchen0cc commented on src/overlaybd/gzindex/CMakeLists.txt
> +add_library(gzindex_lib STATIC ${SOURCE_TAR} )
nit: no need to modify

2023-12-08 03:38 UTC, yuchen0cc commented on src/overlaybd/CMakeLists.txt
> +add_subdirectory(stream_convertor)
nit: no need alternate lines

2023-12-08 03:38 UTC, yuchen0cc commented on src/overlaybd/gzindex/gzip_index_create.cpp
> +// #include "../zfile/crc32/crc32c.h"
nit: remove?

2023-12-08 03:38 UTC, yuchen0cc commented on src/overlaybd/stream_convertor/config.h
> +// struct ServerConfigPara : public App::ConfigGroup  {
nit: remove?

2023-12-08 03:38 UTC, yuchen0cc commented on src/overlaybd/tar/test/CMakeLists.txt
> +add_executable(untar_test test.cpp )
nit

2023-12-08 03:38 UTC, yuchen0cc commented on src/overlaybd/tar/libtar.cpp
> +        if (next != 0) break;
why not test before TH_ISREG(header).
read_header ret: 0-normal, 1-eof, -1-error

2023-12-08 06:56 UTC, yuchen0cc approved these changes
LGTM

2023-12-08 06:57 UTC, merged