[feat.] Support uploading 'output' to registry while merging layers
containerd/overlaybd pull request #349
Opened 2024-09-03 03:18 UTC by BigVan

**What this PR does / why we need it**:
[fix.] enable zfile compress in overlaybd-merge
[feat.] support uploading 'output' to the remote registry while merging layers

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #348 

**Please check the following list**:
- [ ]  Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [ ]  Does this change require a documentation update?
- [ ]  Does this introduce breaking changes that would require an announcement or bumping the major version?
- [ ]  Do all new files have an appropriate license header?

2024-09-03 07:24 UTC, BigVan commented
@WaberZhuang  please take a review

2024-09-03 11:09 UTC, WaberZhuang requested changes

2024-09-03 11:09 UTC, WaberZhuang commented on src/tools/overlaybd-commit.cpp
> +    app.add_option("--upload_bs", upload_bs, "block size for upload, in KB")->default_val(65536); // 64MB
NIT: remove the initial value when declaring
```
// ssize_t upload_bs = 262144;
ssize_t upload_bs = 0;
```

2024-09-09 08:28 UTC, liulanzheng approved these changes
LGMT~

2024-09-09 08:28 UTC, merged