[bugfix] workaround if some SegmentMapping refers to end of tar
containerd/overlaybd pull request #350
Opened 2024-10-18 04:53 UTC by hsiangkao

**What this PR does / why we need it**:
Workaround if some SegmentMapping refers to end of tar (because the mapping doesn't record real remote mapping size), which could happen on EROFS meta indexes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Please check the following list**:
- [ ]  Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [ ]  Does this change require a documentation update?
- [ ]  Does this introduce breaking changes that would require an announcement or bumping the major version?
- [ ]  Do all new files have an appropriate license header?

2024-10-18 05:25 UTC, hsiangkao commented
As [pread(2)](https://man7.org/linux/man-pages/man2/read.2.html) says,
```
On success, the number of bytes read is returned (zero indicates end of file), and the file position is advanced by this number.
It is not an error if this number is smaller than the number of bytes requested; this may happen for example because fewer bytes are actually available right now (maybe because we were close to end-of-file, or because we are reading from a pipe, or from a terminal), or because read() was interrupted by a signal.
```

2024-10-18 09:58 UTC, hsiangkao commented
Before:
![image](https://github.com/user-attachments/assets/a491bf35-8d02-4775-87df-12feaecd3820)
After:
![image](https://github.com/user-attachments/assets/9a27e814-df7f-4eb0-976b-f51132379b41)

2024-10-22 10:32 UTC, WaberZhuang requested changes

2024-10-22 10:32 UTC, WaberZhuang commented on src/overlaybd/lsmt/file.cpp
> +                    size_t ret2 = m_files[m.tag]->pread((char *)buf + ret, size - ret, m.moffset * ALIGNMENT + ret);
check if ret < 0 here

2024-11-12 06:17 UTC, merged